version: "3.9"

services:
  api:
    build: ./api
    links:
      - db_postgres
      # - client
    depends_on:
      - db_postgres
      # - client
    environment:
      DB_HOST: db_postgres
    command:
      # - rake db:create
      # - rake db:migrate
      - rails server
    # entrypoint: ["sh", "/docker-entrypoint.sh"]
    volumes:
      - ./entrypoint.sh:/entrypoint.sh

  # client:
  #   build: ./client
  #   command: yarn dev
  db_postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
