version: "3.9"

services:
  api:
    build: ./api
    links:
      - db_postgres
      # - client
    depends_on:
      - db_postgres
      # - client
    environment:
      DB_HOST: db_postgres
    volumes:
      - ./api:/myapp
    ports:
      - "3000:3000"

  client:
    build: ./client
    command: yarn dev
    ports:
      - "8080:8080"

  db_postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
